create index.html
roman-shevchuk/MyP pull request #1
Opened 2024-01-22 21:58 UTC by roman-shevchuk

2024-01-22 22:03 UTC, roman-shevchuk commented
[My page](https://roman-shevchuk.github.io/MyP/)

2024-01-23 08:15 UTC, roman-shevchuk commented
[My page](https://roman-shevchuk.github.io/MyP/)

2024-01-23 08:46 UTC, OleziO requested changes

2024-01-23 08:46 UTC, OleziO commented on index.html
> +</html>
```suggestion
</html>

```

2024-03-01 13:28 UTC, closed without merging